[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200


build_flags =
    -O2
    -Wall
    -Wno-reorder
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    arduino-libraries/WiFi @ ^1.2.7
